# noqa: E301, E704, E701
"""
BitArray.pyi

This file contains specification documentation for the BitArray class.
That is, the BitArray class is guaranteed to meet the below behavior,
   with the exception of "extra" behavior (e.g., implementations of this
   class may extend another class or have additional methods).
"""
from __future__ import annotations

from typing import TYPE_CHECKING, overload  # typechecking dislikes reexporting overload

try:
    from bytemaker.typing_redirect import (
        Buffer,
        Iterable,
        Iterator,
        Literal,
        MutableSequence,
        Optional,
        Protocol,
        Tuple,
        TypeVar,
        Union,
        runtime_checkable,
    )
except ImportError:
    from typing_redirect import (  # type: ignore
        Buffer,
        Iterable,
        Iterator,
        Literal,
        MutableSequence,
        Optional,
        Protocol,
        Tuple,
        TypeVar,
        Union,
        runtime_checkable,
    )

if TYPE_CHECKING:
    Self = TypeVar("Self", bound="BitArray")
else:
    try:
        from typing_redirect import Self
    except ImportError:
        Self = TypeVar("Self", bound="BitArray")
T = TypeVar("T")

@runtime_checkable
class BitsCastable(Protocol):
    def __Bits__(self, endianness: Literal["little", "big"] = "big") -> BitArray: ...

BitsConstructible = Union["BitArray", bytes, str, Iterable[Literal[0, 1]], BitsCastable]

class BitArray(MutableSequence[Literal[0, 1]]):
    def __new__(
        cls,
        source: Optional[Union[BitsConstructible, int]] = None,
        endianness: Literal["little", "big", "source_else_big"] = "source_else_big",
        buffer: Buffer = None,  # type: ignore
        *args,
        **kwargs,
    ): ...
    def __init__(
        self,
        source: Optional[Union[BitsConstructible, int]] = None,
        encoding: Optional[str] = None,
        errors: Optional[str] = None,
        endianness: Literal["little", "big", "source_else_big"] = "source_else_big",
        buffer: Buffer = None,  # type: ignore
    ) -> None: ...
    @property
    def endianness(self) -> Literal["little", "big"]: ...

    # Conversions
    @classmethod
    def frombin(
        cls: type[Self], string: str, endianness: Literal["little", "big"] = "big"
    ) -> Self: ...
    @classmethod
    def fromhex(
        cls: type[Self], string: str, endianness: Literal["little", "big"] = "big"
    ) -> Self: ...
    @classmethod
    def fromoct(
        cls: type[Self], string: str, endianness: Literal["little", "big"] = "big"
    ) -> Self: ...
    @classmethod
    def fromsize(
        cls: type[Self],
        size: int,
        /,  # We do not know what the name
        # in PEP 467 will be
        endianness: Literal["little", "big"] = "big",
    ) -> Self: ...
    @classmethod
    def from01(
        cls: type[Self],
        string: Iterable[Literal["0", "1"]],
        endianness: Literal["little", "big"] = "big",
    ) -> Self: ...
    @classmethod
    def frombase(
        cls: type[Self],
        string: str,
        base: int,
        endianness: Literal["little", "big"] = "big",
    ) -> Self: ...
    # @classmethod  # todo
    # def from_int(cls, value: int, length: int, signed: bool = True) -> Self: ...
    # This is complicated by PEP 467, which is slightly different functionality
    # @classmethod
    # def from_bytes(
    #     cls: type[Self], bytes: bytes,
    #     endianness: Literal["little", "big"] = "big") -> Self: ...
    @classmethod
    def from_chararray(
        cls: type[Self],
        char_array: str,
        encoding: Union[str, dict[str, BitsConstructible]] = "utf-8",
        endianness: Literal["little", "big"] = "big",
    ) -> Self: ...
    def bin(self, sep: Optional[str] = None, bytes_per_sep: int = 1) -> str: ...
    def hex(self, sep: Optional[str] = None, bytes_per_sep: int = 1) -> str: ...
    def oct(self, sep: Optional[str] = None, bytes_per_sep: int = 1) -> str: ...
    def to01(self, sep: Optional[str] = None, bytes_per_sep: int = 1) -> str: ...
    def tobase(
        self, base: int, sep: Optional[str] = None, bytes_per_sep: int = 1
    ) -> str: ...
    # def to_int(self, signed: bool = True) -> int: ...  # todo
    def to_chararray(
        self, encoding: Union[str, dict[BitsConstructible, str]] = "utf-8"
    ) -> str: ...
    def to_bytes(self) -> bytes: ...

    # Magic Methods and Overloads
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self: Self, other: Self) -> bool: ...
    def __le__(self: Self, other: Self) -> bool: ...
    def __gt__(self: Self, other: Self) -> bool: ...
    def __ge__(self: Self, other: Self) -> bool: ...
    def __add__(self: Self, other: BitsConstructible) -> Self: ...
    def __radd__(self: Self, other: BitsConstructible) -> Self: ...
    def __iadd__(self: Self, other: BitsConstructible) -> Self: ...
    def __mul__(self: Self, count: int) -> Self: ...
    def __imul__(self: Self, count: int) -> Self: ...
    def __rmul__(self: Self, count: int) -> Self: ...
    def __and__(self: Self, other: BitsConstructible) -> Self: ...
    def __rand__(self: Self, other: BitsConstructible) -> Self: ...
    def __iand__(self: Self, other: BitsConstructible) -> Self: ...
    def __or__(self: Self, other: BitsConstructible) -> Self: ...
    def __ror__(self: Self, other: BitsConstructible) -> Self: ...
    def __ior__(self: Self, other: BitsConstructible) -> Self: ...
    def __xor__(self: Self, other: BitsConstructible) -> Self: ...
    def __rxor__(self: Self, other: BitsConstructible) -> Self: ...
    def __ixor__(self: Self, other: BitsConstructible) -> Self: ...
    def __lshift__(self: Self, count: int) -> Self: ...
    def __ilshift__(self: Self, count: int) -> Self: ...
    def __rshift__(self: Self, count: int) -> Self: ...
    def __irshift__(self: Self, count: int) -> Self: ...
    def __invert__(self: Self) -> Self: ...
    # def __neg__(self: Self) -> Self: ...
    def __iter__(self) -> Iterator[Literal[0, 1]]: ...
    def __format__(self, format_spec: str) -> str: ...
    @overload
    def __contains__(self, item: Union[BitsConstructible, Literal[0, 1]]) -> bool: ...
    @overload
    def __contains__(self, item: object) -> bool: ...
    @overload
    def __getitem__(self, key: int) -> Literal[0, 1]: ...
    @overload
    def __getitem__(self: Self, key: Union[slice, Iterable[int]]) -> Self: ...
    @overload
    def __setitem__(self, key: int, value: Literal[0, 1]) -> None: ...
    @overload
    def __setitem__(
        self,
        key: Union[slice, Iterable[int]],
        value: Union[BitsConstructible, Literal[0, 1]],
    ) -> None: ...
    def __delitem__(self, key: Union[int, slice, Iterable[int]]) -> None: ...
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __bytes__(self) -> bytes: ...
    # def __Bits__(self: Self, endianness: str = "big") -> Self: ...
    #     preserve=True default arg
    def __copy__(self: Self) -> Self: ...
    def __deepcopy__(self: Self, memo: dict[int, object]) -> Self: ...
    #     constructor deepcopy default
    # def __reduce__(self
    #   ) -> Tuple[Type[Self], Tuple[Union[bytes, str], str, str, str]]: ... # todo
    # def __reduce_ex__(self, protocol: int
    #   ) -> Tuple[Type[Self], Tuple[Union[bytes, str], str, str, str]]: ... # todo
    # def __getnewargs_ex__(self) -> Tuple[Union[bytes, str], str, str, str]: ... # todo
    # def __getnewargs__(self) -> Tuple[Union[bytes, str], str, str, str]: ... # todo
    # def __getstate__(self) -> Tuple[Union[bytes, str], str, str, str]: ... # todo
    # def __setstate__(self, state: Tuple[Union[bytes, str], str, str, str]
    #   ) -> None: ... # todo
    def __sizeof__(self) -> int: ...

    # Basic Operations
    def append(self, value: int) -> None: ...
    def extend(self, values: BitsConstructible) -> None: ...
    def insert(self, index: int, value: int) -> None: ...
    def pop(self, index: Optional[int] = None) -> Literal[0, 1]: ...
    def remove(self, value: int) -> None: ...
    def clear(self) -> None: ...
    def copy(self: Self) -> Self: ...
    def reverse(self) -> None: ...
    # def swap_endianness(self) -> None: ...

    # Search and Analysis
    def count(
        self,
        value: Union[BitsConstructible, int],
        start: int = 0,
        end: Optional[int] = None,
    ) -> int: ...
    def endswith(
        self, substrings: bytes, start: int = 0, stop: Optional[int] = None
    ) -> bool: ...
    def startswith(
        self, substrings: bytes, start: int = 0, stop: Optional[int] = None
    ) -> bool: ...
    def find(
        self,
        value: Union[BitsConstructible, Literal[0, 1]],
        start: int = 0,
        stop: Optional[int] = None,
    ) -> int: ...
    def rfind(
        self,
        value: Union[BitsConstructible, Literal[0, 1]],
        start: int = 0,
        stop: Optional[int] = None,
    ) -> int: ...
    def index(
        self,
        value: Union[BitsConstructible, Literal[0, 1]],
        start: int = 0,
        stop: Optional[int] = None,
    ) -> int: ...
    def rindex(
        self,
        value: Union[BitsConstructible, Literal[0, 1]],
        start: int = 0,
        stop: Optional[int] = None,
    ) -> int: ...

    # Modification and Translation
    def replace(
        self: Self,
        old: BitsConstructible,
        new: BitsConstructible,
        count: Optional[int] = None,
    ) -> Self: ...
    # def translate(self,
    #   table: List[BitArray] | bytes, delete: Optional[List[BitArray]] = None
    #   ) -> Self: ... # todo
    # def maketrans(self, x, y=None, z=None) -> list[BitArray]: ...  # todo
    def join(self: Self, iterable: Iterable[BitsConstructible]) -> Self: ...
    # def split(self, sep: Optional[bytes] = None, maxsplit: int = -1
    #   ) -> List[bytes]: ... # todo
    # def rsplit(
    #     self, sep: Optional[bytes] = None, maxsplit: int = -1
    # ) -> List[bytes]: ... #todo
    def partition(self, sep: BitArray) -> Tuple[Self, Self, Self]: ...
    def rpartition(self, sep: BitArray) -> Tuple[Self, Self, Self]: ...
    def lstrip(self: Self, bits: Optional[Literal[0, 1]] = None) -> Self: ...
    def rstrip(self: Self, bits: Optional[Literal[0, 1]] = None) -> Self: ...
    def strip(self: Self, bits: Optional[Literal[0, 1]] = None) -> Self: ...

    # Text and Alignment Methods # todo
    # def decode(self, encoding: str = "utf-8", errors: str = "strict") -> str: ...
    # def expandtabs(self, tabsize: int = 8) -> Self: ...
    # def ljust(self, width: int, fillbyte: bytes = b" ") -> Self: ...
    # def rjust(self, width: int, fillbyte: bytes = b" ") -> Self: ...
    # def center(self, width: int, fillbyte: bytes = b" ") -> Self: ...
    # def zfill(self, width: int) -> Self: ...
    # def capitalize(self) -> Self: ...
    # def lower(self) -> Self: ...
    # def swapcase(self) -> Self: ...
    # def title(self) -> Self: ...
    # def upper(self) -> Self: ...
    # def isalnum(self) -> bool: ...
    # def isalpha(self) -> bool: ...
    # def isdigit(self) -> bool: ...
    # def islower(self) -> bool: ...
    # def isspace(self) -> bool: ...s
    # def istitle(self) -> bool: ...
    # def isupper(self) -> bool: ...

    @classmethod
    def cast_if_not_bitarray(  # this should be shallow
        cls: type[Self], obj: BitsConstructible
    ) -> Union[Self, BitArray]: ...

# class FrozenBitArray(frozenbitarray): # todo
#     def __hash__(self) -> int: ...
