"""Type stub for bytemaker.fields (descriptor-typed aliases).

Presents each alias as a descriptor type so type checkers (via
dataclass_transform's descriptor-field rule) type all three channels
truthfully: reads are plain int/float, writes and the synthesized __init__
parameters accept anything the narrowing store accepts - plain ints and,
post-D2, BitType boxes (which satisfy SupportsIndex via Int.__index__).

Widths past 64 resolve at runtime via the module __getattr__; they type as
Any here. Do not use alias names as runtime values (isinstance, etc.) -
they are annotation-only.
"""

from typing import Any, SupportsFloat, SupportsIndex

# Star-import surface: keep identical to the runtime __all__ in fields.py.
# The other declared aliases stay importable by name (and any width resolves
# via __getattr__); they are just not star-exported.
__all__ = [
    "u8",
    "u16",
    "u32",
    "u64",
    "s8",
    "s16",
    "s32",
    "s64",
    "f16",
    "f32",
    "f64",
]

class _UIntAlias:
    def __get__(self, obj: Any, objtype: Any = ...) -> int: ...
    def __set__(self, obj: Any, value: SupportsIndex) -> None: ...

class _SIntAlias:
    def __get__(self, obj: Any, objtype: Any = ...) -> int: ...
    def __set__(self, obj: Any, value: SupportsIndex) -> None: ...

class _FloatAlias:
    def __get__(self, obj: Any, objtype: Any = ...) -> float: ...
    def __set__(self, obj: Any, value: SupportsFloat | SupportsIndex) -> None: ...

class u1(_UIntAlias): ...
class u2(_UIntAlias): ...
class u3(_UIntAlias): ...
class u4(_UIntAlias): ...
class u5(_UIntAlias): ...
class u6(_UIntAlias): ...
class u7(_UIntAlias): ...
class u8(_UIntAlias): ...
class u9(_UIntAlias): ...
class u10(_UIntAlias): ...
class u11(_UIntAlias): ...
class u12(_UIntAlias): ...
class u13(_UIntAlias): ...
class u14(_UIntAlias): ...
class u15(_UIntAlias): ...
class u16(_UIntAlias): ...
class u17(_UIntAlias): ...
class u18(_UIntAlias): ...
class u19(_UIntAlias): ...
class u20(_UIntAlias): ...
class u21(_UIntAlias): ...
class u22(_UIntAlias): ...
class u23(_UIntAlias): ...
class u24(_UIntAlias): ...
class u25(_UIntAlias): ...
class u26(_UIntAlias): ...
class u27(_UIntAlias): ...
class u28(_UIntAlias): ...
class u29(_UIntAlias): ...
class u30(_UIntAlias): ...
class u31(_UIntAlias): ...
class u32(_UIntAlias): ...
class u33(_UIntAlias): ...
class u34(_UIntAlias): ...
class u35(_UIntAlias): ...
class u36(_UIntAlias): ...
class u37(_UIntAlias): ...
class u38(_UIntAlias): ...
class u39(_UIntAlias): ...
class u40(_UIntAlias): ...
class u41(_UIntAlias): ...
class u42(_UIntAlias): ...
class u43(_UIntAlias): ...
class u44(_UIntAlias): ...
class u45(_UIntAlias): ...
class u46(_UIntAlias): ...
class u47(_UIntAlias): ...
class u48(_UIntAlias): ...
class u49(_UIntAlias): ...
class u50(_UIntAlias): ...
class u51(_UIntAlias): ...
class u52(_UIntAlias): ...
class u53(_UIntAlias): ...
class u54(_UIntAlias): ...
class u55(_UIntAlias): ...
class u56(_UIntAlias): ...
class u57(_UIntAlias): ...
class u58(_UIntAlias): ...
class u59(_UIntAlias): ...
class u60(_UIntAlias): ...
class u61(_UIntAlias): ...
class u62(_UIntAlias): ...
class u63(_UIntAlias): ...
class u64(_UIntAlias): ...
class s1(_SIntAlias): ...
class s2(_SIntAlias): ...
class s3(_SIntAlias): ...
class s4(_SIntAlias): ...
class s5(_SIntAlias): ...
class s6(_SIntAlias): ...
class s7(_SIntAlias): ...
class s8(_SIntAlias): ...
class s9(_SIntAlias): ...
class s10(_SIntAlias): ...
class s11(_SIntAlias): ...
class s12(_SIntAlias): ...
class s13(_SIntAlias): ...
class s14(_SIntAlias): ...
class s15(_SIntAlias): ...
class s16(_SIntAlias): ...
class s17(_SIntAlias): ...
class s18(_SIntAlias): ...
class s19(_SIntAlias): ...
class s20(_SIntAlias): ...
class s21(_SIntAlias): ...
class s22(_SIntAlias): ...
class s23(_SIntAlias): ...
class s24(_SIntAlias): ...
class s25(_SIntAlias): ...
class s26(_SIntAlias): ...
class s27(_SIntAlias): ...
class s28(_SIntAlias): ...
class s29(_SIntAlias): ...
class s30(_SIntAlias): ...
class s31(_SIntAlias): ...
class s32(_SIntAlias): ...
class s33(_SIntAlias): ...
class s34(_SIntAlias): ...
class s35(_SIntAlias): ...
class s36(_SIntAlias): ...
class s37(_SIntAlias): ...
class s38(_SIntAlias): ...
class s39(_SIntAlias): ...
class s40(_SIntAlias): ...
class s41(_SIntAlias): ...
class s42(_SIntAlias): ...
class s43(_SIntAlias): ...
class s44(_SIntAlias): ...
class s45(_SIntAlias): ...
class s46(_SIntAlias): ...
class s47(_SIntAlias): ...
class s48(_SIntAlias): ...
class s49(_SIntAlias): ...
class s50(_SIntAlias): ...
class s51(_SIntAlias): ...
class s52(_SIntAlias): ...
class s53(_SIntAlias): ...
class s54(_SIntAlias): ...
class s55(_SIntAlias): ...
class s56(_SIntAlias): ...
class s57(_SIntAlias): ...
class s58(_SIntAlias): ...
class s59(_SIntAlias): ...
class s60(_SIntAlias): ...
class s61(_SIntAlias): ...
class s62(_SIntAlias): ...
class s63(_SIntAlias): ...
class s64(_SIntAlias): ...
class f16(_FloatAlias): ...
class f32(_FloatAlias): ...
class f64(_FloatAlias): ...

def __getattr__(name: str) -> Any: ...
