# Runs PyTest and uploads to CodeCov
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Testing

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    name: PyTest tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13-dev"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install the package along with the optional bitarray speedup
        python -m pip install .[speedups]
        # Install additional dependencies under testing (e.g., pytest)
        python -m pip install .[testing]
        # Install codecov dependency
        python -m pip install pytest-cov
    - name: Test with pytest (bitarray-backed BitVector)
      run: |
        pytest --cov
    - name: Test with pytest (pure-Python BitVector)
      run: |
        python -m pip uninstall -y bitarray
        pytest --cov --cov-append
    - name: Upload results to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
